### ISSUE TITLE
Chore - fix color metadata

### ISSUE THREAD

**Issue by reactive-firewall** [reactive-firewall/shellcheck-scan#6]
## Non-functional change to metadata is needed: the branding color should be changed: let's try `yellow`

```yaml
branding:
  icon: 'code'
  color: 'yellow'
```
